### ISSUE TITLE
UI (top left text) shifts to left when score becomes double digits, triple digits, etc

### ISSUE THREAD

**Issue by jessicayzt** [jessicayzt/cpsc311_proj#12]
Not sure how to fix this one, it's not that noticeable but it's annoying. Maybe we should set a constant number of score digits.

**Comment by laurarodgers** [comment]
We can set HTML formatting within the UI text rather than just printing the string and formatting after maybe?

Should allow us to fine tune alignment

**Comment by jessicayzt** [comment]
Good idea, if you could take this on that'd be great!

**Comment by jessicayzt** [comment]
Tried HTML formatting within the UI text, didn't go well D: Going to commit a bandaid fix for now.
