### ISSUE TITLE
If you die during a key press, the effects of that key down are still in effect

### ISSUE THREAD

**Issue by jessicayzt** [jessicayzt/cpsc311_proj#13]
Reproduce this by running and then dying and not letting go of the right arrow key, Jack'll keep dying repeatedly while crawling to the right and when he eventually falls into a pit, the platforms continue scrolling to the left until only the background is visible.

**Comment by laurarodgers** [comment]
Edit: just putting a note here to consider this bug alongside the flickering animation / direction change lag bug, they are likely related

**Comment by jessicayzt** [comment]
Fixed and tested, it was due to the logic in the update. We did updateGame even if the Game state was Over.
