### ISSUE TITLE
Text at top left appears off-screen

### ISSUE THREAD

**Issue by karenhong** [jessicayzt/cpsc311_proj#3]
Observed on Safari and Chrome.

![screen shot 2017-11-08 at 10 12 14 pm](https://user-images.githubusercontent.com/26354209/32590954-eccac1f2-c4d1-11e7-92cf-01b0f0beaaaf.png)

**Comment by jessicayzt** [comment]
Can test this again!

**Comment by karenhong** [comment]
Issue resolved!
